# Generated by Django 3.0.2 on 2020-02-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('composition', models.TextField(blank=True, null=True, verbose_name='Состав')),
                ('portion', models.FloatField(verbose_name='Количество порций')),
                ('price', models.FloatField(verbose_name='Цена за 100 грамм')),
                ('grams_per_person', models.FloatField(verbose_name='Грамм на человека')),
                ('weight', models.FloatField(verbose_name='Заказ (грамм)')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-published'],
            },
        ),
    ]
