# Generated by Django 3.0.2 on 2020-02-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exsel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='Стоимость заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время'),
        ),
    ]
