# Generated by Django 3.0.3 on 2020-02-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exsel', '0003_auto_20200201_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='portion',
        ),
    ]
