# Generated by Django 3.0.3 on 2020-02-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exsel', '0005_auto_20200203_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
