# Generated by Django 3.0.3 on 2020-02-04 10:20

from django.db import migrations

def reorder(apps, schema_editor):
    MyModel = apps.get_model("exsel", "Product")
    order = 0
    for item in MyModel.objects.all():
        order += 1
        item.my_order = order
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('exsel', '0006_product_my_order'),
    ]


    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['my_order'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RunPython(reorder),
    ]
